### ISSUE TITLE
The system is frozen for 463 / 4800 users

### ISSUE THREAD

**Issue by bakhirev** [Frikallo/stargazerz#2]
A good tool! Thanks! Can you do script more fast?

- for big repository it work more 1 hour
- It stopped working for me on 463 users out of 4800
- Is it possible to add from/to parameters so that I can pick up information in parts?

**Comment by NirDiamant** [comment]
hey @bakhirev, did you figure out any solution to this?

**Comment by bakhirev** [comment]
I don't remember, but I solved the problem) My strategy was:
1. to take a some repository
2. collect contacts
3. send email

I couldn't collect the email quickly and simply (step 2). 
I was unable to send out many personalized emails (step 3).

I will return to this strategy. Maybe it's a feature for your system. Thanks for the work)
